name: DigitalOcean Kubernetes Challenge

on:
  push:
    branches: ["main"]
  # Can be trigger manually
  workflow_dispatch:

defaults:
  run:
  # defaults.run only applies to jobs.<job_id>.steps[*].run
    working-directory: fastapi

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Get Codebase
      - uses: actions/checkout@v2
      # Setup python env
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      # Python Linter
      - name: Python lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501 .
      # Python Security Linter
      - name: Python security lint with bandit
        run: |
          pip install bandit
          bandit -r --skip B101 .
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --system
      # Test
      - name: Test with pytest
        run: pytest
############### Dockerfile ###############
      # Dockerfile Linter: Hadolint
      - name: Dockerfile lint with Hadolint
        run: |
          wget --quiet -O hadolint https://github.com/hadolint/hadolint/releases/download/$VERSION/hadolint-Linux-x86_64
          chmod +x hadolint
          ./hadolint Dockerfile --verbose --failure-threshold error
        env:
          VERSION: v2.8.0
##########################################
      - name: Generate pip requirements file
        run: |
          pipenv lock -r > requirements.txt
      #### This section should be replaced to harbor
      # Dockerhub auth
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: fastapi
          push: true
          tags: treekat71/k8s-challenge:0.1
